name: Deploy to Azure Container App - DEV

on:
  push:
    branches:
      - main

env:
  ACR_NAME: fastapiacrakshay
  RESOURCE_GROUP: rg-fastapi-dev
  CONTAINERAPP_NAME: fastapi-app-dev
  ENV_NAME: fastapi-env-dev
  IMAGE_NAME: fastapi-hello
  LOCATION: eastus

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Build and Push Docker Image
      run: |
        docker build -t $ACR_NAME.azurecr.io/$IMAGE_NAME:latest .
        echo "${{ secrets.ACR_PASSWORD }}" | docker login $ACR_NAME.azurecr.io -u ${{ secrets.ACR_USERNAME }} --password-stdin
        docker push $ACR_NAME.azurecr.io/$IMAGE_NAME:latest
    - name: Restart Container App (to use latest image)
      run: |
        az containerapp update --name $CONTAINERAPP_NAME --resource-group $RESOURCE_GROUP --image $ACR_NAME.azurecr.io/$IMAGE_NAME:latest